import type { NumberQuizItem } from "./types";

export const NUMBER_QUIZ_NORMAL_ITEMS: NumberQuizItem[] = [
  {
    id: "1",
    question: "水素(H)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "水素は1族の元素。",
  },
  {
    id: "2",
    question: "リチウム(Li)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "リチウムは1族の元素。",
  },
  {
    id: "3",
    question: "ベリリウム(Be)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ベリリウムは2族の元素。",
  },
  {
    id: "4",
    question: "ホウ素(B)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "ホウ素は13族の元素。",
  },
  {
    id: "5",
    question: "炭素(C)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "炭素は14族の元素。",
  },
  {
    id: "6",
    question: "窒素(N)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "窒素は15族の元素。",
  },
  {
    id: "7",
    question: "ナトリウム(Na)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "ナトリウムは1族の元素。",
  },
  {
    id: "8",
    question: "マグネシウム(Mg)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "マグネシウムは2族の元素。",
  },
  {
    id: "9",
    question: "アルミニウム(Al)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "アルミニウムは13族の元素。",
  },
  {
    id: "10",
    question: "ケイ素(Si)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "ケイ素は14族の元素。",
  },
  {
    id: "11",
    question: "リン(P)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "リンは15族の元素。",
  },
  {
    id: "12",
    question: "カリウム(K)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "カリウムは1族の元素。",
  },
  {
    id: "13",
    question: "カルシウム(Ca)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "カルシウムは2族の元素。",
  },
  {
    id: "14",
    question: "スカンジウム(Sc)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "スカンジウムは3族の元素。",
  },
  {
    id: "15",
    question: "チタン(Ti)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "チタンは4族の元素。",
  },
  {
    id: "16",
    question: "バナジウム(V)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "バナジウムは5族の元素。",
  },
  {
    id: "17",
    question: "クロム(Cr)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "クロムは6族の元素。",
  },
  {
    id: "18",
    question: "マンガン(Mn)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "マンガンは7族の元素。",
  },
  {
    id: "19",
    question: "鉄(Fe)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "鉄は8族の元素。",
  },
  {
    id: "20",
    question: "コバルト(Co)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "コバルトは9族の元素。",
  },
  {
    id: "21",
    question: "ニッケル(Ni)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "ニッケルは10族の元素。",
  },
  {
    id: "22",
    question: "銅(Cu)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "銅は11族の元素。",
  },
  {
    id: "23",
    question: "亜鉛(Zn)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "亜鉛は12族の元素。",
  },
  {
    id: "24",
    question: "ガリウム(Ga)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "ガリウムは13族の元素。",
  },
  {
    id: "25",
    question: "ゲルマニウム(Ge)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "ゲルマニウムは14族の元素。",
  },
  {
    id: "26",
    question: "ヒ素(As)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "ヒ素は15族の元素。",
  },
  {
    id: "27",
    question: "ルビジウム(Rb)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "ルビジウムは1族の元素。",
  },
  {
    id: "28",
    question: "ストロンチウム(Sr)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ストロンチウムは2族の元素。",
  },
  {
    id: "29",
    question: "イットリウム(Y)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "イットリウムは3族の元素。",
  },
  {
    id: "30",
    question: "ジルコニウム(Zr)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "ジルコニウムは4族の元素。",
  },
  {
    id: "31",
    question: "ニオブ(Nb)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ニオブは5族の元素。",
  },
  {
    id: "32",
    question: "モリブデン(Mo)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "モリブデンは6族の元素。",
  },
  {
    id: "33",
    question: "テクネチウム(Tc)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "テクネチウムは7族の元素。",
  },
  {
    id: "34",
    question: "ルテニウム(Ru)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "ルテニウムは8族の元素。",
  },
  {
    id: "35",
    question: "ロジウム(Rh)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "ロジウムは9族の元素。",
  },
  {
    id: "36",
    question: "パラジウム(Pd)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "パラジウムは10族の元素。",
  },
  {
    id: "37",
    question: "銀(Ag)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "銀は11族の元素。",
  },
  {
    id: "38",
    question: "カドミウム(Cd)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "カドミウムは12族の元素。",
  },
  {
    id: "39",
    question: "インジウム(In)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "インジウムは13族の元素。",
  },
  {
    id: "40",
    question: "スズ(Sn)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "スズは14族の元素。",
  },
  {
    id: "41",
    question: "アンチモン(Sb)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "アンチモンは15族の元素。",
  },
  {
    id: "42",
    question: "セシウム(Cs)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "セシウムは1族の元素。",
  },
  {
    id: "43",
    question: "バリウム(Ba)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "バリウムは2族の元素。",
  },
  {
    id: "44",
    question: "ハフニウム(Hf)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "ハフニウムは4族の元素。",
  },
  {
    id: "45",
    question: "タンタル(Ta)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "タンタルは5族の元素。",
  },
  {
    id: "46",
    question: "タングステン(W)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "タングステンは6族の元素。",
  },
  {
    id: "47",
    question: "レニウム(Re)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "レニウムは7族の元素。",
  },
  {
    id: "48",
    question: "オスミウム(Os)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "オスミウムは8族の元素。",
  },
  {
    id: "49",
    question: "イリジウム(Ir)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "イリジウムは9族の元素。",
  },
  {
    id: "50",
    question: "白金(Pt)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "白金は10族の元素。",
  },
  {
    id: "51",
    question: "金(Au)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "金は11族の元素。",
  },
  {
    id: "52",
    question: "水銀(Hg)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "水銀は12族の元素。",
  },
  {
    id: "53",
    question: "タリウム(Tl)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "タリウムは13族の元素。",
  },
  {
    id: "54",
    question: "鉛(Pb)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "鉛は14族の元素。",
  },
  {
    id: "55",
    question: "ビスマス(Bi)は周期表の何族の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "ビスマスは15族の元素。",
  },
  {
    id: "56",
    question: "水素(H)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "水素は第1周期の元素。",
  },
  {
    id: "57",
    question: "ヘリウム(He)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "ヘリウムは第1周期の元素。",
  },
  {
    id: "58",
    question: "リチウム(Li)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "リチウムは第2周期の元素。",
  },
  {
    id: "59",
    question: "ベリリウム(Be)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ベリリウムは第2周期の元素。",
  },
  {
    id: "60",
    question: "ホウ素(B)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ホウ素は第2周期の元素。",
  },
  {
    id: "61",
    question: "炭素(C)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "炭素は第2周期の元素。",
  },
  {
    id: "62",
    question: "窒素(N)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "窒素は第2周期の元素。",
  },
  {
    id: "63",
    question: "酸素(O)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "酸素は第2周期の元素。",
  },
  {
    id: "64",
    question: "フッ素(F)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "フッ素は第2周期の元素。",
  },
  {
    id: "65",
    question: "ネオン(Ne)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ネオンは第2周期の元素。",
  },
  {
    id: "66",
    question: "ナトリウム(Na)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "ナトリウムは第3周期の元素。",
  },
  {
    id: "67",
    question: "マグネシウム(Mg)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "マグネシウムは第3周期の元素。",
  },
  {
    id: "68",
    question: "アルミニウム(Al)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "アルミニウムは第3周期の元素。",
  },
  {
    id: "69",
    question: "ケイ素(Si)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "ケイ素は第3周期の元素。",
  },
  {
    id: "70",
    question: "リン(P)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "リンは第3周期の元素。",
  },
  {
    id: "71",
    question: "硫黄(S)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "硫黄は第3周期の元素。",
  },
  {
    id: "72",
    question: "塩素(Cl)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "塩素は第3周期の元素。",
  },
  {
    id: "73",
    question: "アルゴン(Ar)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "アルゴンは第3周期の元素。",
  },
  {
    id: "74",
    question: "カリウム(K)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "カリウムは第4周期の元素。",
  },
  {
    id: "75",
    question: "カルシウム(Ca)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "カルシウムは第4周期の元素。",
  },
  {
    id: "76",
    question: "スカンジウム(Sc)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "スカンジウムは第4周期の元素。",
  },
  {
    id: "77",
    question: "チタン(Ti)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "チタンは第4周期の元素。",
  },
  {
    id: "78",
    question: "バナジウム(V)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "バナジウムは第4周期の元素。",
  },
  {
    id: "79",
    question: "クロム(Cr)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "クロムは第4周期の元素。",
  },
  {
    id: "80",
    question: "マンガン(Mn)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "マンガンは第4周期の元素。",
  },
  {
    id: "81",
    question: "鉄(Fe)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "鉄は第4周期の元素。",
  },
  {
    id: "82",
    question: "コバルト(Co)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "コバルトは第4周期の元素。",
  },
  {
    id: "83",
    question: "ニッケル(Ni)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "ニッケルは第4周期の元素。",
  },
  {
    id: "84",
    question: "銅(Cu)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "銅は第4周期の元素。",
  },
  {
    id: "85",
    question: "亜鉛(Zn)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "亜鉛は第4周期の元素。",
  },
  {
    id: "86",
    question: "国連安全保障理事会の理事国は全部で何か国?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "常任5・非常任10の計15か国。",
  },
  {
    id: "87",
    question: "国連安全保障理事会の常任理事国は何か国?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "米・英・仏・露・中の5か国。",
  },
  {
    id: "88",
    question: "国連安全保障理事会の非常任理事国は何か国?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "任期2年の非常任理事国は10か国。",
  },
  {
    id: "89",
    question: "国連の公用語はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "英語・仏語・スペイン語・ロシア語・中国語・アラビア語の6言語。",
  },
  {
    id: "90",
    question: "新約聖書における十二使徒の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二使徒は12人。",
  },
  {
    id: "91",
    question: "サッカー日本代表のワールドカップ出場回数は?(2022年大会まで)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "1998年から2022年まで通算7回連続出場。",
  },
  {
    id: "92",
    question: "ラグビーワールドカップの開催回数は?(2019年大会まで)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "1987年の第1回から2019年大会まで通算9回。",
  },
  {
    id: "93",
    question: "ノーベル賞の自然科学系の部門(物理学・化学・生理学医学)はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "物理学・化学・生理学医学の3部門。",
  },
  {
    id: "94",
    question: "十二支が一巡するのは何年?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二支は12年で一巡する。",
  },
  {
    id: "95",
    question: "冬季オリンピック札幌大会の日本開催回数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "1972年の1回(2024年時点)。",
  },
  {
    id: "96",
    question: "G7の参加国数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "米英仏独伊加日の7か国。",
  },
  {
    id: "97",
    question: "五大栄養素はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "炭水化物・脂質・タンパク質・ビタミン・ミネラルの5つ。",
  },
  {
    id: "98",
    question: "剣道の有効打突部位はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "面・小手・胴・突きの4か所。",
  },
  {
    id: "99",
    question: "将棋の持ち駒になる駒の種類は?(玉を除く)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "歩・香・桂・銀・金・角・飛の7種類。",
  },
  {
    id: "100",
    question: "柔道の階級数は?(男子・オリンピック)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "60kg級から100kg超級までの7階級。",
  },
];
