import type { NumberQuizItem } from "./types";

export const NUMBER_QUIZ_EASY_ITEMS: NumberQuizItem[] = [
  {
    id: "1",
    question: "十二支で「子」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "子から数えて子は1番目。",
  },
  {
    id: "2",
    question: "十二支で「丑」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "子から数えて丑は2番目。",
  },
  {
    id: "3",
    question: "十二支で「寅」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "子から数えて寅は3番目。",
  },
  {
    id: "4",
    question: "十二支で「卯」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "子から数えて卯は4番目。",
  },
  {
    id: "5",
    question: "十二支で「辰」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "子から数えて辰は5番目。",
  },
  {
    id: "6",
    question: "十二支で「巳」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "子から数えて巳は6番目。",
  },
  {
    id: "7",
    question: "十二支で「午」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "子から数えて午は7番目。",
  },
  {
    id: "8",
    question: "十二支で「未」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "子から数えて未は8番目。",
  },
  {
    id: "9",
    question: "十二支で「申」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "子から数えて申は9番目。",
  },
  {
    id: "10",
    question: "十二支で「酉」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "子から数えて酉は10番目。",
  },
  {
    id: "11",
    question: "十二支で「戌」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "子から数えて戌は11番目。",
  },
  {
    id: "12",
    question: "十二支で「亥」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "子から数えて亥は12番目。",
  },
  {
    id: "13",
    question: "三角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "三角形の辺は3本。",
  },
  {
    id: "14",
    question: "四角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "四角形の辺は4本。",
  },
  {
    id: "15",
    question: "五角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "五角形の辺は5本。",
  },
  {
    id: "16",
    question: "六角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "六角形の辺は6本。",
  },
  {
    id: "17",
    question: "七角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "七角形の辺は7本。",
  },
  {
    id: "18",
    question: "八角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "八角形の辺は8本。",
  },
  {
    id: "19",
    question: "九角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "九角形の辺は9本。",
  },
  {
    id: "20",
    question: "十角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "十角形の辺は10本。",
  },
  {
    id: "21",
    question: "十一角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "十一角形の辺は11本。",
  },
  {
    id: "22",
    question: "十二角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二角形の辺は12本。",
  },
  {
    id: "23",
    question: "十三角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "十三角形の辺は13本。",
  },
  {
    id: "24",
    question: "十四角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "十四角形の辺は14本。",
  },
  {
    id: "25",
    question: "十五角形の辺は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "十五角形の辺は15本。",
  },
  {
    id: "26",
    question: "四角形の対角線は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "四角形の対角線の本数はn(n-3)/2の公式より2本。",
  },
  {
    id: "27",
    question: "五角形の対角線は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "五角形の対角線の本数はn(n-3)/2の公式より5本。",
  },
  {
    id: "28",
    question: "六角形の対角線は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "六角形の対角線の本数はn(n-3)/2の公式より9本。",
  },
  {
    id: "29",
    question: "七角形の対角線は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4", "8"],
    explanation: "七角形の対角線の本数はn(n-3)/2の公式より14本。",
  },
  {
    id: "30",
    question: "正四面体の面はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "正四面体の面は4面。",
  },
  {
    id: "31",
    question: "正四面体の辺はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "正四面体の辺は6本。",
  },
  {
    id: "32",
    question: "正四面体の頂点はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "正四面体の頂点は4つ。",
  },
  {
    id: "33",
    question: "立方体(正六面体)の面はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "立方体の面は6面。",
  },
  {
    id: "34",
    question: "立方体(正六面体)の辺はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "立方体の辺は12本。",
  },
  {
    id: "35",
    question: "立方体(正六面体)の頂点はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "立方体の頂点は8つ。",
  },
  {
    id: "36",
    question: "正八面体の面はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "正八面体の面は8面。",
  },
  {
    id: "37",
    question: "正八面体の辺はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "正八面体の辺は12本。",
  },
  {
    id: "38",
    question: "正八面体の頂点はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "正八面体の頂点は6つ。",
  },
  {
    id: "39",
    question: "正十二面体の面はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "正十二面体の面は12面。",
  },
  {
    id: "40",
    question: "正二十面体の頂点はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "正二十面体の頂点は12個。",
  },
  {
    id: "41",
    question: "サッカーで1チームがフィールドに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "サッカーは1チーム11人制。",
  },
  {
    id: "42",
    question: "バスケットボールで1チームがコートに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "バスケットボールは1チーム5人制。",
  },
  {
    id: "43",
    question: "バレーボールで1チームがコートに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "バレーボールは1チーム6人制。",
  },
  {
    id: "44",
    question: "野球で1チームの守備位置(ポジション)は何個?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "投手から右翼手まで守備位置は9個。",
  },
  {
    id: "45",
    question: "ラグビー(15人制)の1チームの人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4", "8"],
    explanation: "15人制ラグビーは1チーム15人。",
  },
  {
    id: "46",
    question: "ラグビー(7人制)の1チームの人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "7人制ラグビーは1チーム7人。",
  },
  {
    id: "47",
    question: "ハンドボールで1チームがコートに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "ハンドボールは1チーム7人制(GK含む)。",
  },
  {
    id: "48",
    question: "アイスホッケーで1チームがリンクに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "アイスホッケーは1チーム6人制(GK含む)。",
  },
  {
    id: "49",
    question: "アメリカンフットボールで1チームがフィールドに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "アメフトは1チーム11人制。",
  },
  {
    id: "50",
    question: "クリケットで1チームの人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "クリケットは1チーム11人制。",
  },
  {
    id: "51",
    question: "フットサルで1チームがコートに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "フットサルは1チーム5人制(GK含む)。",
  },
  {
    id: "52",
    question: "水球で1チームがプールに入れる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "水球は1チーム7人制(GK含む)。",
  },
  {
    id: "53",
    question: "1年の四季の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "春夏秋冬の4つ。",
  },
  {
    id: "54",
    question: "1週間は何日?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "1週間は7日。",
  },
  {
    id: "55",
    question: "1年は何ヶ月?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "1年は12ヶ月。",
  },
  {
    id: "56",
    question: "血液型(ABO式)は何種類?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "A・B・O・ABの4種類。",
  },
  {
    id: "57",
    question: "オリンピックのシンボルマークの輪は何個?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "五輪マークは輪が5つ。",
  },
  {
    id: "58",
    question: "トランプのスート(マーク)は何種類?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "スペード・ハート・ダイヤ・クラブの4種類。",
  },
  {
    id: "59",
    question: "物質の三態(固体・液体・気体)は何種類?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "固体・液体・気体の3種類。",
  },
  {
    id: "60",
    question: "太陽系の惑星は何個?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "水星〜海王星の8個。",
  },
  {
    id: "61",
    question: "日本語の母音(あいうえお)は何個?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "あ・い・う・え・おの5個。",
  },
  {
    id: "62",
    question: "世界の七不思議(古代)は何個?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "古代の七不思議は7つ。",
  },
  {
    id: "63",
    question: "七福神は何人?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "恵比寿・大黒天など7人の神様。",
  },
  {
    id: "64",
    question: "「白雪姫」に登場する小人は何人?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "7人の小人が登場する。",
  },
  {
    id: "65",
    question: "日本で虹は一般的に何色とされる?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "日本では虹は7色とされる。",
  },
  {
    id: "66",
    question: "新約聖書の十二使徒は何人?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二使徒は12人。",
  },
  {
    id: "67",
    question: "黄道十二星座は何種類?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "黄道十二星座は12種類。",
  },
  {
    id: "68",
    question: "1ダースはいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "1ダースは12個。",
  },
  {
    id: "69",
    question: "さいころの目は最大いくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "さいころの目は1〜6。",
  },
  {
    id: "70",
    question: "1年の四半期の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "1年は4つの四半期に分けられる。",
  },
  {
    id: "71",
    question: "冬季オリンピック札幌大会の日本開催回数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "1972年の1回(2024年時点)。",
  },
  {
    id: "72",
    question: "G7の参加国数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "米英仏独伊加日の7か国。",
  },
  {
    id: "73",
    question: "将棋の持ち駒になる駒の種類は?(玉を除く)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "歩・香・桂・銀・金・角・飛の7種類。",
  },
  {
    id: "74",
    question: "トランプ1組(ジョーカー抜き)の1スートの枚数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "A〜Kまで13枚。",
  },
  {
    id: "75",
    question: "オセロの初期配置の石の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "黒2個・白2個の計4個。",
  },
  {
    id: "76",
    question: "将棋の駒の基本種類は?(玉を含み成り駒を除く)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "歩・香・桂・銀・金・角・飛・玉の8種類。",
  },
  {
    id: "77",
    question: "剣道の有効打突部位はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "面・小手・胴・突きの4か所。",
  },
  {
    id: "78",
    question: "1年のうち偶数月(2,4,6,8,10,12月)は何ヶ月?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "2,4,6,8,10,12月の6ヶ月。",
  },
  {
    id: "79",
    question: "1年のうち31日ある月は何ヶ月?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "1,3,5,7,8,10,12月の7ヶ月。",
  },
  {
    id: "80",
    question: "1年のうち30日ある月は何ヶ月?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "4,6,9,11月の4ヶ月。",
  },
  {
    id: "81",
    question: "片手の指は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "片手の指は5本。",
  },
  {
    id: "82",
    question: "両手の指は合計何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "両手で指は10本。",
  },
  {
    id: "83",
    question: "片足の指は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "片足の指は5本。",
  },
  {
    id: "84",
    question: "立方体の空間対角線(内部を貫く対角線)は何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "立方体の空間対角線は4本。",
  },
  {
    id: "85",
    question: "三角形の角(頂点)はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "三角形の頂点は3つ。",
  },
  {
    id: "86",
    question: "正方形の角(頂点)はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "正方形の頂点は4つ。",
  },
  {
    id: "87",
    question: "東京オリンピックの夏季開催回数は?(2021年時点)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "1964年と2021年の2回。",
  },
  {
    id: "88",
    question: "サッカー日本代表のワールドカップ出場回数は?(2022年大会まで)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "1998年から2022年まで通算7回。",
  },
  {
    id: "89",
    question: "ラグビーワールドカップの開催回数は?(2019年大会まで)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "1987年から2019年まで通算9回。",
  },
  {
    id: "90",
    question: "卓球の1ゲームの先取点数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "2001年以降の国際ルールで11点先取。",
  },
  {
    id: "91",
    question: "サッカーの1試合の交代枠は何人まで?(2022年以降)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "2022年以降、基本5人まで交代可能。",
  },
  {
    id: "92",
    question: "柔道の階級数は?(男子・オリンピック)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "60kg級から100kg超級までの7階級。",
  },
  {
    id: "93",
    question: "十二支が一巡するのは何年?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二支は12年で一巡する。",
  },
  {
    id: "94",
    question: "周期表の周期(自然界に存在する周期)はいくつ?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "第1〜第7周期まである。",
  },
  {
    id: "95",
    question: "五十音の行の数は?(ん・拗音を除く)",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "あ行からわ行までの10行。",
  },
  {
    id: "96",
    question: "オリンピックの開催間隔(夏季)は何年おき?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "夏季五輪は4年に一度開催。",
  },
  {
    id: "97",
    question: "野球で1イニングのアウト数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "1イニングは3アウトで交代。",
  },
  {
    id: "98",
    question: "バスケットボール(NBA)の1試合のピリオド数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "NBAは1試合4ピリオド制。",
  },
  {
    id: "99",
    question: "両足の指は合計何本?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "両足で指は10本。",
  },
  {
    id: "100",
    question: "五角形の内角(頂点)の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "五角形の頂点は5つ。",
  },
  {
    id: "101",
    question: "十角形の内角(頂点)の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "十角形の頂点は10個。",
  },
];
