import type { NumberQuizItem } from "./types";

export const NUMBER_QUIZ_HARD_ITEMS: NumberQuizItem[] = [
  {
    id: "1",
    question: "酸素(O)は周期表の何族の元素?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["1", "3", "5", "7"],
    explanation: "酸素は16族(酸素族)の元素。",
  },
  {
    id: "2",
    question: "硫黄(S)は周期表の何族の元素?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["1", "3", "5", "7"],
    explanation: "硫黄は16族(酸素族)の元素。",
  },
  {
    id: "3",
    question: "セレン(Se)は周期表の何族の元素?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["1", "3", "5", "7"],
    explanation: "セレンは16族(酸素族)の元素。",
  },
  {
    id: "4",
    question: "テルル(Te)は周期表の何族の元素?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["1", "3", "5", "7"],
    explanation: "テルルは16族(酸素族)の元素。",
  },
  {
    id: "5",
    question: "ポロニウム(Po)は周期表の何族の元素?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["1", "3", "5", "7"],
    explanation: "ポロニウムは16族(酸素族)の元素。",
  },
  {
    id: "6",
    question: "ヘリウム(He)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "ヘリウムは18族(希ガス)の元素。",
  },
  {
    id: "7",
    question: "ネオン(Ne)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "ネオンは18族(希ガス)の元素。",
  },
  {
    id: "8",
    question: "アルゴン(Ar)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "アルゴンは18族(希ガス)の元素。",
  },
  {
    id: "9",
    question: "クリプトン(Kr)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "クリプトンは18族(希ガス)の元素。",
  },
  {
    id: "10",
    question: "キセノン(Xe)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "キセノンは18族(希ガス)の元素。",
  },
  {
    id: "11",
    question: "ラドン(Rn)は周期表の何族の元素?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "ラドンは18族(希ガス)の元素。",
  },
  {
    id: "12",
    question: "フッ素(F)は周期表の何族の元素?",
    choices: ["1", "2", "6", "8"],
    correctChoices: ["1", "2", "6", "8"],
    explanation: "フッ素は17族(ハロゲン)の元素。",
  },
  {
    id: "13",
    question: "塩素(Cl)は周期表の何族の元素?",
    choices: ["1", "2", "6", "8"],
    correctChoices: ["1", "2", "6", "8"],
    explanation: "塩素は17族(ハロゲン)の元素。",
  },
  {
    id: "14",
    question: "臭素(Br)は周期表の何族の元素?",
    choices: ["1", "2", "6", "8"],
    correctChoices: ["1", "2", "6", "8"],
    explanation: "臭素は17族(ハロゲン)の元素。",
  },
  {
    id: "15",
    question: "ヨウ素(I)は周期表の何族の元素?",
    choices: ["1", "2", "6", "8"],
    correctChoices: ["1", "2", "6", "8"],
    explanation: "ヨウ素は17族(ハロゲン)の元素。",
  },
  {
    id: "16",
    question: "アスタチン(At)は周期表の何族の元素?",
    choices: ["1", "2", "6", "8"],
    correctChoices: ["1", "2", "6", "8"],
    explanation: "アスタチンは17族(ハロゲン)の元素。",
  },
  {
    id: "17",
    question: "ヘリウム(He)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "ヘリウムは第1周期の元素。",
  },
  {
    id: "18",
    question: "酸素(O)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "酸素は第2周期の元素。",
  },
  {
    id: "19",
    question: "フッ素(F)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "フッ素は第2周期の元素。",
  },
  {
    id: "20",
    question: "ネオン(Ne)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "ネオンは第2周期の元素。",
  },
  {
    id: "21",
    question: "硫黄(S)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "硫黄は第3周期の元素。",
  },
  {
    id: "22",
    question: "塩素(Cl)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "塩素は第3周期の元素。",
  },
  {
    id: "23",
    question: "アルゴン(Ar)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "アルゴンは第3周期の元素。",
  },
  {
    id: "24",
    question: "セレン(Se)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "セレンは第4周期の元素。",
  },
  {
    id: "25",
    question: "臭素(Br)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "臭素は第4周期の元素。",
  },
  {
    id: "26",
    question: "クリプトン(Kr)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "クリプトンは第4周期の元素。",
  },
  {
    id: "27",
    question: "テルル(Te)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "テルルは第5周期の元素。",
  },
  {
    id: "28",
    question: "ヨウ素(I)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ヨウ素は第5周期の元素。",
  },
  {
    id: "29",
    question: "キセノン(Xe)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "キセノンは第5周期の元素。",
  },
  {
    id: "30",
    question: "ポロニウム(Po)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "ポロニウムは第6周期の元素。",
  },
  {
    id: "31",
    question: "アスタチン(At)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "アスタチンは第6周期の元素。",
  },
  {
    id: "32",
    question: "ラドン(Rn)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "ラドンは第6周期の元素。",
  },
  {
    id: "33",
    question: "水素(H)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["1"],
    explanation: "水素は第1周期の元素。",
  },
  {
    id: "34",
    question: "リチウム(Li)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["2"],
    explanation: "リチウムは第2周期の元素。",
  },
  {
    id: "35",
    question: "ベリリウム(Be)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["2"],
    explanation: "ベリリウムは第2周期の元素。",
  },
  {
    id: "36",
    question: "ホウ素(B)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["2"],
    explanation: "ホウ素は第2周期の元素。",
  },
  {
    id: "37",
    question: "炭素(C)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["2"],
    explanation: "炭素は第2周期の元素。",
  },
  {
    id: "38",
    question: "窒素(N)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["2"],
    explanation: "窒素は第2周期の元素。",
  },
  {
    id: "39",
    question: "ナトリウム(Na)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "ナトリウムは第3周期の元素。",
  },
  {
    id: "40",
    question: "マグネシウム(Mg)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "マグネシウムは第3周期の元素。",
  },
  {
    id: "41",
    question: "アルミニウム(Al)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "アルミニウムは第3周期の元素。",
  },
  {
    id: "42",
    question: "ケイ素(Si)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "ケイ素は第3周期の元素。",
  },
  {
    id: "43",
    question: "リン(P)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "リンは第3周期の元素。",
  },
  {
    id: "44",
    question: "カリウム(K)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "カリウムは第4周期の元素。",
  },
  {
    id: "45",
    question: "カルシウム(Ca)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "カルシウムは第4周期の元素。",
  },
  {
    id: "46",
    question: "スカンジウム(Sc)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "スカンジウムは第4周期の元素。",
  },
  {
    id: "47",
    question: "チタン(Ti)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "チタンは第4周期の元素。",
  },
  {
    id: "48",
    question: "バナジウム(V)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "バナジウムは第4周期の元素。",
  },
  {
    id: "49",
    question: "クロム(Cr)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "クロムは第4周期の元素。",
  },
  {
    id: "50",
    question: "マンガン(Mn)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "マンガンは第4周期の元素。",
  },
  {
    id: "51",
    question: "鉄(Fe)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "鉄は第4周期の元素。",
  },
  {
    id: "52",
    question: "コバルト(Co)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "コバルトは第4周期の元素。",
  },
  {
    id: "53",
    question: "ニッケル(Ni)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "ニッケルは第4周期の元素。",
  },
  {
    id: "54",
    question: "銅(Cu)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "銅は第4周期の元素。",
  },
  {
    id: "55",
    question: "亜鉛(Zn)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "亜鉛は第4周期の元素。",
  },
  {
    id: "56",
    question: "ガリウム(Ga)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "ガリウムは第4周期の元素。",
  },
  {
    id: "57",
    question: "ゲルマニウム(Ge)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "ゲルマニウムは第4周期の元素。",
  },
  {
    id: "58",
    question: "ヒ素(As)は周期表の第何周期の元素?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "ヒ素は第4周期の元素。",
  },
  {
    id: "59",
    question: "ルビジウム(Rb)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ルビジウムは第5周期の元素。",
  },
  {
    id: "60",
    question: "ストロンチウム(Sr)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ストロンチウムは第5周期の元素。",
  },
  {
    id: "61",
    question: "イットリウム(Y)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "イットリウムは第5周期の元素。",
  },
  {
    id: "62",
    question: "ジルコニウム(Zr)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ジルコニウムは第5周期の元素。",
  },
  {
    id: "63",
    question: "ニオブ(Nb)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ニオブは第5周期の元素。",
  },
  {
    id: "64",
    question: "モリブデン(Mo)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "モリブデンは第5周期の元素。",
  },
  {
    id: "65",
    question: "テクネチウム(Tc)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "テクネチウムは第5周期の元素。",
  },
  {
    id: "66",
    question: "ルテニウム(Ru)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ルテニウムは第5周期の元素。",
  },
  {
    id: "67",
    question: "ロジウム(Rh)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "ロジウムは第5周期の元素。",
  },
  {
    id: "68",
    question: "パラジウム(Pd)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "パラジウムは第5周期の元素。",
  },
  {
    id: "69",
    question: "銀(Ag)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "銀は第5周期の元素。",
  },
  {
    id: "70",
    question: "カドミウム(Cd)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "カドミウムは第5周期の元素。",
  },
  {
    id: "71",
    question: "インジウム(In)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "インジウムは第5周期の元素。",
  },
  {
    id: "72",
    question: "スズ(Sn)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "スズは第5周期の元素。",
  },
  {
    id: "73",
    question: "アンチモン(Sb)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "アンチモンは第5周期の元素。",
  },
  {
    id: "74",
    question: "セシウム(Cs)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "セシウムは第6周期の元素。",
  },
  {
    id: "75",
    question: "バリウム(Ba)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "バリウムは第6周期の元素。",
  },
  {
    id: "76",
    question: "ハフニウム(Hf)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "ハフニウムは第6周期の元素。",
  },
  {
    id: "77",
    question: "タンタル(Ta)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "タンタルは第6周期の元素。",
  },
  {
    id: "78",
    question: "タングステン(W)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "タングステンは第6周期の元素。",
  },
  {
    id: "79",
    question: "レニウム(Re)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "レニウムは第6周期の元素。",
  },
  {
    id: "80",
    question: "オスミウム(Os)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "オスミウムは第6周期の元素。",
  },
  {
    id: "81",
    question: "イリジウム(Ir)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "イリジウムは第6周期の元素。",
  },
  {
    id: "82",
    question: "白金(Pt)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "白金は第6周期の元素。",
  },
  {
    id: "83",
    question: "金(Au)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "金は第6周期の元素。",
  },
  {
    id: "84",
    question: "水銀(Hg)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "水銀は第6周期の元素。",
  },
  {
    id: "85",
    question: "タリウム(Tl)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "タリウムは第6周期の元素。",
  },
  {
    id: "86",
    question: "鉛(Pb)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "鉛は第6周期の元素。",
  },
  {
    id: "87",
    question: "ビスマス(Bi)は周期表の第何周期の元素?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "ビスマスは第6周期の元素。",
  },
  {
    id: "88",
    question: "十二支で「子」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1"],
    explanation: "子から数えて子は1番目。",
  },
  {
    id: "89",
    question: "十二支で「丑」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2"],
    explanation: "子から数えて丑は2番目。",
  },
  {
    id: "90",
    question: "十二支で「寅」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2"],
    explanation: "子から数えて寅は3番目。",
  },
  {
    id: "91",
    question: "十二支で「卯」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4"],
    explanation: "子から数えて卯は4番目。",
  },
  {
    id: "92",
    question: "十二支で「辰」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4"],
    explanation: "子から数えて辰は5番目。",
  },
  {
    id: "93",
    question: "十二支で「巳」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "4"],
    explanation: "子から数えて巳は6番目。",
  },
  {
    id: "94",
    question: "十二支で「午」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "4"],
    explanation: "子から数えて午は7番目。",
  },
  {
    id: "95",
    question: "十二支で「未」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["8"],
    explanation: "子から数えて未は8番目。",
  },
  {
    id: "96",
    question: "十二支で「申」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "8"],
    explanation: "子から数えて申は9番目。",
  },
  {
    id: "97",
    question: "十二支で「酉」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "子から数えて酉は10番目。",
  },
  {
    id: "98",
    question: "十二支で「戌」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "子から数えて戌は11番目。",
  },
  {
    id: "99",
    question: "十二支で「亥」は何番目?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "子から数えて亥は12番目。",
  },
  {
    id: "100",
    question: "正十二面体の辺は何本?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["10", "20"],
    explanation: "正十二面体の辺は30本。",
  },
  {
    id: "101",
    question: "正二十面体の辺は何本?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["10", "20"],
    explanation: "正二十面体の辺は30本。",
  },
  {
    id: "102",
    question: "正十二面体の頂点はいくつ?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["20"],
    explanation: "正十二面体の頂点は20個。",
  },
  {
    id: "103",
    question: "正二十面体の面はいくつ?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["20"],
    explanation: "正二十面体の面は20面。",
  },
  {
    id: "104",
    question: "十角形の対角線は何本?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["5", "10", "20"],
    explanation: "十角形の対角線はn(n-3)/2の公式より35本。",
  },
  {
    id: "105",
    question: "干支(十干十二支の組み合わせ)が一巡するのは何年?",
    choices: ["5", "10", "20", "40"],
    correctChoices: ["20", "40"],
    explanation: "十二支自体は12年で一巡するが、十干と組み合わせた干支(えと)が一巡し同じ組み合わせに戻るのは60年(還暦)。",
  },
  {
    id: "106",
    question: "ゴルフの1ラウンドのホール数は?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["4", "6", "8"],
    explanation: "ゴルフの1ラウンドは18ホール。",
  },
  {
    id: "107",
    question: "将棋の持ち駒になる駒の種類は?(玉を除く)",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["7"],
    explanation: "歩・香・桂・銀・金・角・飛の7種類。",
  },
  {
    id: "108",
    question: "トランプ1組(ジョーカー抜き)の1スートの枚数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "4", "8"],
    explanation: "A〜Kまで13枚。",
  },
  {
    id: "109",
    question: "剣道の有効打突部位はいくつ?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["4"],
    explanation: "面・小手・胴・突きの4か所。",
  },
  {
    id: "110",
    question: "柔道の階級数は?(男子・オリンピック)",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["7"],
    explanation: "60kg級から100kg超級までの7階級。",
  },
  {
    id: "111",
    question: "野球で1イニングのアウト数は?",
    choices: ["1", "2", "3", "4"],
    correctChoices: ["3"],
    explanation: "1イニングは3アウトで交代。",
  },
  {
    id: "112",
    question: "G7の参加国数は?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["7"],
    explanation: "米英仏独伊加日の7か国。",
  },
  {
    id: "113",
    question: "国連の公用語はいくつ?",
    choices: ["2", "4", "6", "8"],
    correctChoices: ["6"],
    explanation: "英語・仏語・スペイン語・ロシア語・中国語・アラビア語の6言語。",
  },
  {
    id: "114",
    question: "五大栄養素はいくつ?",
    choices: ["1", "3", "5", "7"],
    correctChoices: ["5"],
    explanation: "炭水化物・脂質・タンパク質・ビタミン・ミネラルの5つ。",
  },
  {
    id: "115",
    question: "新約聖書における十二使徒の数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "十二使徒は12人。",
  },
  {
    id: "116",
    question: "ラクロス(男子)で1チームがフィールドに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["2", "8"],
    explanation: "男子ラクロスは1チーム10人制。",
  },
  {
    id: "117",
    question: "ラクロス(女子)で1チームがフィールドに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["4", "8"],
    explanation: "女子ラクロスは1チーム12人制。",
  },
  {
    id: "118",
    question: "フィールドホッケーで1チームがピッチに立てる人数は?",
    choices: ["1", "2", "4", "8"],
    correctChoices: ["1", "2", "8"],
    explanation: "フィールドホッケーは1チーム11人制。",
  },
];
