/**
 * 漢字スクエア: 上下左右に漢字が書かれていて、中央のマスに漢字を1字入れると、
 * それぞれの方向と組み合わさって二字熟語が完成するパズル。
 *
 * 組み合わせの向きは以下の固定ルール:
 *   - 上(top)   + 中央(answer) = 上→中央 の順で読む熟語  (例: 天 + 気 = 天気)
 *   - 左(left)  + 中央(answer) = 左→中央 の順で読む熟語  (例: 病 + 気 = 病気)
 *   - 中央(answer) + 右(right) = 中央→右 の順で読む熟語  (例: 気 + 分 = 気分)
 *   - 中央(answer) + 下(bottom) = 中央→下 の順で読む熟語 (例: 気 + 圧 = 気圧)
 *
 * 問題を追加したいときは、この配列に1件足すだけでよい。
 * `words` には確認表示用に完成する熟語をそのまま書いておく(読み方の向きを
 * プログラム側で自動生成せず、データとして明示することで表記ミスを防ぐ)。
 */
export interface KanjiSquarePuzzle {
  id: string;
  top: string;
  bottom: string;
  left: string;
  right: string;
  /** 中央マスに入る正解の漢字(1字) */
  answer: string;
  /** 完成する熟語(表示・答え合わせの参考用) */
  words: {
    top: string; // 上 + 中央
    left: string; // 左 + 中央
    right: string; // 中央 + 右
    bottom: string; // 中央 + 下
  };
}

export const KANJI_SQUARE_PUZZLES: KanjiSquarePuzzle[] = [
  {
    id: "set1-1",
    top: "白",
    left: "暗",
    right: "海",
    bottom: "量",
    answer: "雲",
    words: { top: "白雲", left: "暗雲", right: "雲海", bottom: "雲量" },
  },
  {
    id: "set1-2",
    top: "顔",
    left: "変",
    right: "彩",
    bottom: "紙",
    answer: "色",
    words: { top: "顔色", left: "変色", right: "色彩", bottom: "色紙" },
  },
  {
    id: "set1-3",
    top: "人",
    left: "変",
    right: "式",
    bottom: "態",
    answer: "形",
    words: { top: "人形", left: "変形", right: "形式", bottom: "形態" },
  },
  {
    id: "set1-4",
    top: "発",
    left: "説",
    right: "日",
    bottom: "暗",
    answer: "明",
    words: { top: "発明", left: "説明", right: "明日", bottom: "明暗" },
  },
  {
    id: "set1-5",
    top: "益",
    left: "昆",
    right: "歯",
    bottom: "害",
    answer: "虫",
    words: { top: "益虫", left: "昆虫", right: "虫歯", bottom: "虫害" },
  },
  {
    id: "set1-6",
    top: "乳",
    left: "義",
    right: "科",
    bottom: "痛",
    answer: "歯",
    words: { top: "乳歯", left: "義歯", right: "歯科", bottom: "歯痛" },
  },
  {
    id: "set1-7",
    top: "白",
    left: "野",
    right: "居",
    bottom: "類",
    answer: "鳥",
    words: { top: "白鳥", left: "野鳥", right: "鳥居", bottom: "鳥類" },
  },
  {
    id: "set1-8",
    top: "金",
    left: "川",
    right: "介",
    bottom: "群",
    answer: "魚",
    words: { top: "金魚", left: "川魚", right: "魚介", bottom: "魚群" },
  },
  {
    id: "set1-9",
    top: "番",
    left: "愛",
    right: "歯",
    bottom: "種",
    answer: "犬",
    words: { top: "番犬", left: "愛犬", right: "犬歯", bottom: "犬種" },
  },
  {
    id: "set1-10",
    top: "愛",
    left: "子",
    right: "背",
    bottom: "舌",
    answer: "猫",
    words: { top: "愛猫", left: "子猫", right: "猫背", bottom: "猫舌" },
  },
  {
    id: "set1-11",
    top: "色",
    left: "用",
    right: "面",
    bottom: "袋",
    answer: "紙",
    words: { top: "色紙", left: "用紙", right: "紙面", bottom: "紙袋" },
  },
  {
    id: "set1-12",
    top: "毛",
    left: "綿",
    right: "口",
    bottom: "目",
    answer: "糸",
    words: { top: "毛糸", left: "綿糸", right: "糸口", bottom: "糸目" },
  },
  {
    id: "set1-13",
    top: "食",
    left: "岩",
    right: "分",
    bottom: "水",
    answer: "塩",
    words: { top: "食塩", left: "岩塩", right: "塩分", bottom: "塩水" },
  },
  {
    id: "set1-14",
    top: "塩",
    left: "炭",
    right: "素",
    bottom: "味",
    answer: "酸",
    words: { top: "塩酸", left: "炭酸", right: "酸素", bottom: "酸味" },
  },
  {
    id: "set1-15",
    top: "木",
    left: "石",
    right: "酸",
    bottom: "火",
    answer: "炭",
    words: { top: "木炭", left: "石炭", right: "炭酸", bottom: "炭火" },
  },
  {
    id: "set1-16",
    top: "満",
    left: "干",
    right: "風",
    bottom: "流",
    answer: "潮",
    words: { top: "満潮", left: "干潮", right: "潮風", bottom: "潮流" },
  },
  {
    id: "set1-17",
    top: "薄",
    left: "流",
    right: "山",
    bottom: "点",
    answer: "氷",
    words: { top: "薄氷", left: "流氷", right: "氷山", bottom: "氷点" },
  },
  {
    id: "set1-18",
    top: "温",
    left: "鉱",
    right: "水",
    bottom: "源",
    answer: "泉",
    words: { top: "温泉", left: "鉱泉", right: "泉水", bottom: "泉源" },
  },
  {
    id: "set1-19",
    top: "紅",
    left: "緑",
    right: "道",
    bottom: "碗",
    answer: "茶",
    words: { top: "紅茶", left: "緑茶", right: "茶道", bottom: "茶碗" },
  },
  {
    id: "set1-20",
    top: "夕",
    left: "赤",
    right: "粒",
    bottom: "時",
    answer: "飯",
    words: { top: "夕飯", left: "赤飯", right: "飯粒", bottom: "飯時" },
  },
  {
    id: "set2-1",
    top: "社",
    left: "面",
    right: "議",
    bottom: "場",
    answer: "会",
    words: { top: "社会", left: "面会", right: "会議", bottom: "会場" },
  },
  {
    id: "set2-2",
    top: "空",
    left: "元",
    right: "分",
    bottom: "候",
    answer: "気",
    words: { top: "空気", left: "元気", right: "気分", bottom: "気候" },
  },
  {
    id: "set2-3",
    top: "大",
    left: "入",
    right: "校",
    bottom: "生",
    answer: "学",
    words: { top: "大学", left: "入学", right: "学校", bottom: "学生" },
  },
  {
    id: "set2-4",
    top: "学",
    left: "母",
    right: "長",
    bottom: "庭",
    answer: "校",
    words: { top: "学校", left: "母校", right: "校長", bottom: "校庭" },
  },
  {
    id: "set2-5",
    top: "電",
    left: "馬",
    right: "輪",
    bottom: "庫",
    answer: "車",
    words: { top: "電車", left: "馬車", right: "車輪", bottom: "車庫" },
  },
  {
    id: "set2-6",
    top: "花",
    left: "出",
    right: "山",
    bottom: "傷",
    answer: "火",
    words: { top: "花火", left: "出火", right: "火山", bottom: "火傷" },
  },
  {
    id: "set2-7",
    top: "香",
    left: "海",
    right: "道",
    bottom: "分",
    answer: "水",
    words: { top: "香水", left: "海水", right: "水道", bottom: "水分" },
  },
  {
    id: "set2-8",
    top: "登",
    left: "火",
    right: "脈",
    bottom: "頂",
    answer: "山",
    words: { top: "登山", left: "火山", right: "山脈", bottom: "山頂" },
  },
  {
    id: "set2-9",
    top: "水",
    left: "歩",
    right: "具",
    bottom: "路",
    answer: "道",
    words: { top: "水道", left: "歩道", right: "道具", bottom: "道路" },
  },
  {
    id: "set2-10",
    top: "気",
    left: "十",
    right: "担",
    bottom: "野",
    answer: "分",
    words: { top: "気分", left: "十分", right: "分担", bottom: "分野" },
  },
  {
    id: "set2-11",
    top: "開",
    left: "生",
    right: "粉",
    bottom: "束",
    answer: "花",
    words: { top: "開花", left: "生花", right: "花粉", bottom: "花束" },
  },
  {
    id: "set2-12",
    top: "火",
    left: "仕",
    right: "件",
    bottom: "情",
    answer: "事",
    words: { top: "火事", left: "仕事", right: "事件", bottom: "事情" },
  },
  {
    id: "set2-13",
    top: "工",
    left: "卒",
    right: "務",
    bottom: "界",
    answer: "業",
    words: { top: "工業", left: "卒業", right: "業務", bottom: "業界" },
  },
  {
    id: "set2-14",
    top: "学",
    left: "誕",
    right: "活",
    bottom: "産",
    answer: "生",
    words: { top: "学生", left: "誕生", right: "生活", bottom: "生産" },
  },
  {
    id: "set2-15",
    top: "生",
    left: "復",
    right: "動",
    bottom: "力",
    answer: "活",
    words: { top: "生活", left: "復活", right: "活動", bottom: "活力" },
  },
  {
    id: "set2-16",
    top: "活",
    left: "自",
    right: "物",
    bottom: "作",
    answer: "動",
    words: { top: "活動", left: "自動", right: "動物", bottom: "動作" },
  },
  {
    id: "set2-17",
    top: "動",
    left: "建",
    right: "語",
    bottom: "価",
    answer: "物",
    words: { top: "動物", left: "建物", right: "物語", bottom: "物価" },
  },
  {
    id: "set2-18",
    top: "物",
    left: "英",
    right: "学",
    bottom: "句",
    answer: "語",
    words: { top: "物語", left: "英語", right: "語学", bottom: "語句" },
  },
  {
    id: "set2-19",
    top: "中",
    left: "安",
    right: "配",
    bottom: "理",
    answer: "心",
    words: { top: "中心", left: "安心", right: "心配", bottom: "心理" },
  },
  {
    id: "set2-20",
    top: "心",
    left: "分",
    right: "達",
    bottom: "置",
    answer: "配",
    words: { top: "心配", left: "分配", right: "配達", bottom: "配置" },
  },
  {
    id: "set2-21",
    top: "心",
    left: "料",
    right: "由",
    bottom: "解",
    answer: "理",
    words: { top: "心理", left: "料理", right: "理由", bottom: "理解" },
  },
  {
    id: "set2-22",
    top: "理",
    left: "自",
    right: "来",
    bottom: "緒",
    answer: "由",
    words: { top: "理由", left: "自由", right: "由来", bottom: "由緒" },
  },
  {
    id: "set2-23",
    top: "電",
    left: "努",
    right: "士",
    bottom: "量",
    answer: "力",
    words: { top: "電力", left: "努力", right: "力士", bottom: "力量" },
  },
  {
    id: "set2-24",
    top: "停",
    left: "感",
    right: "話",
    bottom: "気",
    answer: "電",
    words: { top: "停電", left: "感電", right: "電話", bottom: "電気" },
  },
  {
    id: "set2-25",
    top: "電",
    left: "会",
    right: "題",
    bottom: "術",
    answer: "話",
    words: { top: "電話", left: "会話", right: "話題", bottom: "話術" },
  },
  {
    id: "set2-26",
    top: "話",
    left: "問",
    right: "名",
    bottom: "材",
    answer: "題",
    words: { top: "話題", left: "問題", right: "題名", bottom: "題材" },
  },
  {
    id: "set2-27",
    top: "学",
    left: "訪",
    right: "題",
    bottom: "答",
    answer: "問",
    words: { top: "学問", left: "訪問", right: "問題", bottom: "問答" },
  },
  {
    id: "set2-28",
    top: "問",
    left: "回",
    right: "案",
    bottom: "申",
    answer: "答",
    words: { top: "問答", left: "回答", right: "答案", bottom: "答申" },
  },
  {
    id: "set2-29",
    top: "今",
    left: "前",
    right: "転",
    bottom: "答",
    answer: "回",
    words: { top: "今回", left: "前回", right: "回転", bottom: "回答" },
  },
  {
    id: "set2-30",
    top: "回",
    left: "逆",
    right: "校",
    bottom: "勤",
    answer: "転",
    words: { top: "回転", left: "逆転", right: "転校", bottom: "転勤" },
  },
  {
    id: "set2-31",
    top: "転",
    left: "出",
    right: "務",
    bottom: "勉",
    answer: "勤",
    words: { top: "転勤", left: "出勤", right: "勤務", bottom: "勤勉" },
  },
  {
    id: "set2-32",
    top: "生",
    left: "財",
    right: "業",
    bottom: "地",
    answer: "産",
    words: { top: "生産", left: "財産", right: "産業", bottom: "産地" },
  },
  {
    id: "set2-33",
    top: "家",
    left: "蓄",
    right: "産",
    bottom: "布",
    answer: "財",
    words: { top: "家財", left: "蓄財", right: "財産", bottom: "財布" },
  },
  {
    id: "set2-34",
    top: "財",
    left: "配",
    right: "団",
    bottom: "地",
    answer: "布",
    words: { top: "財布", left: "配布", right: "布団", bottom: "布地" },
  },
  {
    id: "set2-35",
    top: "布",
    left: "集",
    right: "体",
    bottom: "結",
    answer: "団",
    words: { top: "布団", left: "集団", right: "団体", bottom: "団結" },
  },
  {
    id: "set2-36",
    top: "団",
    left: "全",
    right: "育",
    bottom: "重",
    answer: "体",
    words: { top: "団体", left: "全体", right: "体育", bottom: "体重" },
  },
  {
    id: "set2-37",
    top: "体",
    left: "教",
    right: "児",
    bottom: "成",
    answer: "育",
    words: { top: "体育", left: "教育", right: "育児", bottom: "育成" },
  },
  {
    id: "set2-38",
    top: "宗",
    left: "布",
    right: "室",
    bottom: "師",
    answer: "教",
    words: { top: "宗教", left: "布教", right: "教室", bottom: "教師" },
  },
  {
    id: "set2-39",
    top: "教",
    left: "温",
    right: "内",
    bottom: "長",
    answer: "室",
    words: { top: "教室", left: "温室", right: "室内", bottom: "室長" },
  },
  {
    id: "set2-40",
    top: "室",
    left: "国",
    right: "容",
    bottom: "科",
    answer: "内",
    words: { top: "室内", left: "国内", right: "内容", bottom: "内科" },
  },
  {
    id: "set2-41",
    top: "中",
    left: "外",
    right: "語",
    bottom: "民",
    answer: "国",
    words: { top: "中国", left: "外国", right: "国語", bottom: "国民" },
  },
  {
    id: "set2-42",
    top: "国",
    left: "市",
    right: "主",
    bottom: "族",
    answer: "民",
    words: { top: "国民", left: "市民", right: "民主", bottom: "民族" },
  },
  {
    id: "set2-43",
    top: "民",
    left: "君",
    right: "人",
    bottom: "義",
    answer: "主",
    words: { top: "民主", left: "君主", right: "主人", bottom: "主義" },
  },
  {
    id: "set2-44",
    top: "主",
    left: "意",
    right: "務",
    bottom: "理",
    answer: "義",
    words: { top: "主義", left: "意義", right: "義務", bottom: "義理" },
  },
  {
    id: "set2-45",
    top: "決",
    left: "注",
    right: "味",
    bottom: "見",
    answer: "意",
    words: { top: "決意", left: "注意", right: "意味", bottom: "意見" },
  },
  {
    id: "set2-46",
    top: "意",
    left: "発",
    right: "学",
    bottom: "本",
    answer: "見",
    words: { top: "意見", left: "発見", right: "見学", bottom: "見本" },
  },
  {
    id: "set2-47",
    top: "出",
    left: "開",
    right: "表",
    bottom: "明",
    answer: "発",
    words: { top: "出発", left: "開発", right: "発表", bottom: "発明" },
  },
  {
    id: "set2-48",
    top: "発",
    left: "代",
    right: "現",
    bottom: "情",
    answer: "表",
    words: { top: "発表", left: "代表", right: "表現", bottom: "表情" },
  },
  {
    id: "set2-49",
    top: "時",
    left: "世",
    right: "表",
    bottom: "金",
    answer: "代",
    words: { top: "時代", left: "世代", right: "代表", bottom: "代金" },
  },
  {
    id: "set2-50",
    top: "当",
    left: "同",
    right: "間",
    bottom: "代",
    answer: "時",
    words: { top: "当時", left: "同時", right: "時間", bottom: "時代" },
  },
  {
    id: "set2-51",
    top: "時",
    left: "空",
    right: "隔",
    bottom: "食",
    answer: "間",
    words: { top: "時間", left: "空間", right: "間隔", bottom: "間食" },
  },
  {
    id: "set2-52",
    top: "航",
    left: "上",
    right: "気",
    bottom: "港",
    answer: "空",
    words: { top: "航空", left: "上空", right: "空気", bottom: "空港" },
  },
  {
    id: "set2-53",
    top: "空",
    left: "出",
    right: "町",
    bottom: "湾",
    answer: "港",
    words: { top: "空港", left: "出港", right: "港町", bottom: "港湾" },
  },
  {
    id: "set2-54",
    top: "港",
    left: "下",
    right: "内",
    bottom: "村",
    answer: "町",
    words: { top: "港町", left: "下町", right: "町内", bottom: "町村" },
  },
  {
    id: "set2-55",
    top: "町",
    left: "農",
    right: "長",
    bottom: "落",
    answer: "村",
    words: { top: "町村", left: "農村", right: "村長", bottom: "村落" },
  },
  {
    id: "set2-56",
    top: "酪",
    left: "富",
    right: "業",
    bottom: "家",
    answer: "農",
    words: { top: "酪農", left: "富農", right: "農業", bottom: "農家" },
  },
  {
    id: "set2-57",
    top: "農",
    left: "作",
    right: "族",
    bottom: "庭",
    answer: "家",
    words: { top: "農家", left: "作家", right: "家族", bottom: "家庭" },
  },
  {
    id: "set2-58",
    top: "家",
    left: "校",
    right: "園",
    bottom: "木",
    answer: "庭",
    words: { top: "家庭", left: "校庭", right: "庭園", bottom: "庭木" },
  },
  {
    id: "set2-59",
    top: "庭",
    left: "公",
    right: "芸",
    bottom: "児",
    answer: "園",
    words: { top: "庭園", left: "公園", right: "園芸", bottom: "園児" },
  },
  {
    id: "set2-60",
    top: "園",
    left: "工",
    right: "術",
    bottom: "能",
    answer: "芸",
    words: { top: "園芸", left: "工芸", right: "芸術", bottom: "芸能" },
  },
  {
    id: "set2-61",
    top: "芸",
    left: "手",
    right: "後",
    bottom: "中",
    answer: "術",
    words: { top: "芸術", left: "手術", right: "術後", bottom: "術中" },
  },
  {
    id: "set2-62",
    top: "大",
    left: "植",
    right: "材",
    bottom: "造",
    answer: "木",
    words: { top: "大木", left: "植木", right: "木材", bottom: "木造" },
  },
  {
    id: "set2-63",
    top: "化",
    left: "宝",
    right: "油",
    bottom: "炭",
    answer: "石",
    words: { top: "化石", left: "宝石", right: "石油", bottom: "石炭" },
  },
  {
    id: "set2-64",
    top: "現",
    left: "資",
    right: "額",
    bottom: "庫",
    answer: "金",
    words: { top: "現金", left: "資金", right: "金額", bottom: "金庫" },
  },
  {
    id: "set2-65",
    top: "白",
    left: "水",
    right: "行",
    bottom: "河",
    answer: "銀",
    words: { top: "白銀", left: "水銀", right: "銀行", bottom: "銀河" },
  },
  {
    id: "set2-66",
    top: "銀",
    left: "旅",
    right: "動",
    bottom: "事",
    answer: "行",
    words: { top: "銀行", left: "旅行", right: "行動", bottom: "行事" },
  },
  {
    id: "set2-67",
    top: "客",
    left: "造",
    right: "長",
    bottom: "員",
    answer: "船",
    words: { top: "客船", left: "造船", right: "船長", bottom: "船員" },
  },
  {
    id: "set2-68",
    top: "観",
    left: "乗",
    right: "席",
    bottom: "間",
    answer: "客",
    words: { top: "観客", left: "乗客", right: "客席", bottom: "客間" },
  },
  {
    id: "set2-69",
    top: "客",
    left: "出",
    right: "順",
    bottom: "次",
    answer: "席",
    words: { top: "客席", left: "出席", right: "席順", bottom: "席次" },
  },
  {
    id: "set2-70",
    top: "主",
    left: "客",
    right: "光",
    bottom: "察",
    answer: "観",
    words: { top: "主観", left: "客観", right: "観光", bottom: "観察" },
  },
  {
    id: "set2-71",
    top: "観",
    left: "日",
    right: "線",
    bottom: "景",
    answer: "光",
    words: { top: "観光", left: "日光", right: "光線", bottom: "光景" },
  },
  {
    id: "set2-72",
    top: "休",
    left: "毎",
    right: "光",
    bottom: "記",
    answer: "日",
    words: { top: "休日", left: "毎日", right: "日光", bottom: "日記" },
  },
  {
    id: "set2-73",
    top: "日",
    left: "暗",
    right: "録",
    bottom: "念",
    answer: "記",
    words: { top: "日記", left: "暗記", right: "記録", bottom: "記念" },
  },
  {
    id: "set2-74",
    top: "記",
    left: "登",
    right: "音",
    bottom: "画",
    answer: "録",
    words: { top: "記録", left: "登録", right: "録音", bottom: "録画" },
  },
  {
    id: "set2-75",
    top: "録",
    left: "発",
    right: "楽",
    bottom: "色",
    answer: "音",
    words: { top: "録音", left: "発音", right: "音楽", bottom: "音色" },
  },
  {
    id: "set2-76",
    top: "音",
    left: "娯",
    right: "器",
    bottom: "園",
    answer: "楽",
    words: { top: "音楽", left: "娯楽", right: "楽器", bottom: "楽園" },
  },
  {
    id: "set2-77",
    top: "楽",
    left: "食",
    right: "具",
    bottom: "官",
    answer: "器",
    words: { top: "楽器", left: "食器", right: "器具", bottom: "器官" },
  },
  {
    id: "set2-78",
    top: "器",
    left: "長",
    right: "庁",
    bottom: "僚",
    answer: "官",
    words: { top: "器官", left: "長官", right: "官庁", bottom: "官僚" },
  },
  {
    id: "set2-79",
    top: "他",
    left: "全",
    right: "庁",
    bottom: "立",
    answer: "県",
    words: { top: "他県", left: "全県", right: "県庁", bottom: "県立" },
  },
  {
    id: "set2-80",
    top: "県",
    left: "独",
    right: "場",
    bottom: "体",
    answer: "立",
    words: { top: "県立", left: "独立", right: "立場", bottom: "立体" },
  },
  {
    id: "set2-81",
    top: "立",
    left: "工",
    right: "所",
    bottom: "面",
    answer: "場",
    words: { top: "立場", left: "工場", right: "場所", bottom: "場面" },
  },
  {
    id: "set2-82",
    top: "場",
    left: "近",
    right: "有",
    bottom: "得",
    answer: "所",
    words: { top: "場所", left: "近所", right: "所有", bottom: "所得" },
  },
  {
    id: "set2-83",
    top: "所",
    left: "共",
    right: "名",
    bottom: "料",
    answer: "有",
    words: { top: "所有", left: "共有", right: "有名", bottom: "有料" },
  },
  {
    id: "set2-84",
    top: "有",
    left: "氏",
    right: "人",
    bottom: "前",
    answer: "名",
    words: { top: "有名", left: "氏名", right: "名人", bottom: "名前" },
  },
  {
    id: "set2-85",
    top: "名",
    left: "午",
    right: "進",
    bottom: "提",
    answer: "前",
    words: { top: "名前", left: "午前", right: "前進", bottom: "前提" },
  },
  {
    id: "set2-86",
    top: "前",
    left: "行",
    right: "化",
    bottom: "路",
    answer: "進",
    words: { top: "前進", left: "行進", right: "進化", bottom: "進路" },
  },
  {
    id: "set2-87",
    top: "進",
    left: "文",
    right: "石",
    bottom: "粧",
    answer: "化",
    words: { top: "進化", left: "文化", right: "化石", bottom: "化粧" },
  },
  {
    id: "set2-88",
    top: "作",
    left: "論",
    right: "化",
    bottom: "章",
    answer: "文",
    words: { top: "作文", left: "論文", right: "文化", bottom: "文章" },
  },
  {
    id: "set2-89",
    top: "議",
    left: "世",
    right: "文",
    bottom: "理",
    answer: "論",
    words: { top: "議論", left: "世論", right: "論文", bottom: "論理" },
  },
  {
    id: "set2-90",
    top: "出",
    left: "中",
    right: "界",
    bottom: "代",
    answer: "世",
    words: { top: "出世", left: "中世", right: "世界", bottom: "世代" },
  },
  {
    id: "set2-91",
    top: "意",
    left: "興",
    right: "方",
    bottom: "覚",
    answer: "味",
    words: { top: "意味", left: "興味", right: "味方", bottom: "味覚" },
  },
  {
    id: "set2-92",
    top: "味",
    left: "地",
    right: "法",
    bottom: "向",
    answer: "方",
    words: { top: "味方", left: "地方", right: "方法", bottom: "方向" },
  },
  {
    id: "set2-93",
    top: "方",
    left: "文",
    right: "律",
    bottom: "則",
    answer: "法",
    words: { top: "方法", left: "文法", right: "法律", bottom: "法則" },
  },
  {
    id: "set2-94",
    top: "法",
    left: "規",
    right: "儀",
    bottom: "令",
    answer: "律",
    words: { top: "法律", left: "規律", right: "律儀", bottom: "律令" },
  },
  {
    id: "set2-95",
    top: "法",
    left: "新",
    right: "則",
    bottom: "模",
    answer: "規",
    words: { top: "法規", left: "新規", right: "規則", bottom: "規模" },
  },
  {
    id: "set2-96",
    top: "生",
    left: "運",
    right: "令",
    bottom: "中",
    answer: "命",
    words: { top: "生命", left: "運命", right: "命令", bottom: "命中" },
  },
  {
    id: "set2-97",
    top: "高",
    left: "草",
    right: "因",
    bottom: "料",
    answer: "原",
    words: { top: "高原", left: "草原", right: "原因", bottom: "原料" },
  },
  {
    id: "set2-98",
    top: "原",
    left: "起",
    right: "果",
    bottom: "子",
    answer: "因",
    words: { top: "原因", left: "起因", right: "因果", bottom: "因子" },
  },
  {
    id: "set2-99",
    top: "因",
    left: "結",
    right: "実",
    bottom: "物",
    answer: "果",
    words: { top: "因果", left: "結果", right: "果実", bottom: "果物" },
  },
  {
    id: "set2-100",
    top: "団",
    left: "連",
    right: "果",
    bottom: "論",
    answer: "結",
    words: { top: "団結", left: "連結", right: "結果", bottom: "結論" },
  },
  {
    id: "set3-1",
    top: "去",
    left: "学",
    right: "末",
    bottom: "代",
    answer: "年",
    words: { top: "去年", left: "学年", right: "年末", bottom: "年代" },
  },
  {
    id: "set3-2",
    top: "正",
    left: "毎",
    right: "日",
    bottom: "光",
    answer: "月",
    words: { top: "正月", left: "毎月", right: "月日", bottom: "月光" },
  },
  {
    id: "set3-3",
    top: "今",
    left: "毎",
    right: "末",
    bottom: "間",
    answer: "週",
    words: { top: "今週", left: "毎週", right: "週末", bottom: "週間" },
  },
  {
    id: "set3-4",
    top: "毎",
    left: "早",
    right: "食",
    bottom: "日",
    answer: "朝",
    words: { top: "毎朝", left: "早朝", right: "朝食", bottom: "朝日" },
  },
  {
    id: "set3-5",
    top: "今",
    left: "深",
    right: "景",
    bottom: "間",
    answer: "夜",
    words: { top: "今夜", left: "深夜", right: "夜景", bottom: "夜間" },
  },
  {
    id: "set3-6",
    top: "大",
    left: "小",
    right: "具",
    bottom: "天",
    answer: "雨",
    words: { top: "大雨", left: "小雨", right: "雨具", bottom: "雨天" },
  },
  {
    id: "set3-7",
    top: "大",
    left: "初",
    right: "国",
    bottom: "山",
    answer: "雪",
    words: { top: "大雪", left: "初雪", right: "雪国", bottom: "雪山" },
  },
  {
    id: "set3-8",
    top: "台",
    left: "強",
    right: "船",
    bottom: "景",
    answer: "風",
    words: { top: "台風", left: "強風", right: "風船", bottom: "風景" },
  },
  {
    id: "set3-9",
    top: "雨",
    left: "晴",
    right: "気",
    bottom: "才",
    answer: "天",
    words: { top: "雨天", left: "晴天", right: "天気", bottom: "天才" },
  },
  {
    id: "set3-10",
    top: "産",
    left: "土",
    right: "図",
    bottom: "方",
    answer: "地",
    words: { top: "産地", left: "土地", right: "地図", bottom: "地方" },
  },
  {
    id: "set3-11",
    top: "河",
    left: "小",
    right: "原",
    bottom: "岸",
    answer: "川",
    words: { top: "河川", left: "小川", right: "川原", bottom: "川岸" },
  },
  {
    id: "set3-12",
    top: "森",
    left: "山",
    right: "業",
    bottom: "道",
    answer: "林",
    words: { top: "森林", left: "山林", right: "林業", bottom: "林道" },
  },
  {
    id: "set3-13",
    top: "開",
    left: "来",
    right: "員",
    bottom: "長",
    answer: "店",
    words: { top: "開店", left: "来店", right: "店員", bottom: "店長" },
  },
  {
    id: "set3-14",
    top: "部",
    left: "家",
    right: "根",
    bottom: "外",
    answer: "屋",
    words: { top: "部屋", left: "家屋", right: "屋根", bottom: "屋外" },
  },
  {
    id: "set3-15",
    top: "車",
    left: "天",
    right: "口",
    bottom: "辺",
    answer: "窓",
    words: { top: "車窓", left: "天窓", right: "窓口", bottom: "窓辺" },
  },
  {
    id: "set3-16",
    top: "用",
    left: "手",
    right: "面",
    bottom: "袋",
    answer: "紙",
    words: { top: "用紙", left: "手紙", right: "紙面", bottom: "紙袋" },
  },
  {
    id: "set3-17",
    top: "鉛",
    left: "毛",
    right: "記",
    bottom: "箱",
    answer: "筆",
    words: { top: "鉛筆", left: "毛筆", right: "筆記", bottom: "筆箱" },
  },
  {
    id: "set3-18",
    top: "数",
    left: "漢",
    right: "体",
    bottom: "幕",
    answer: "字",
    words: { top: "数字", left: "漢字", right: "字体", bottom: "字幕" },
  },
  {
    id: "set3-19",
    top: "算",
    left: "人",
    right: "字",
    bottom: "学",
    answer: "数",
    words: { top: "算数", left: "人数", right: "数字", bottom: "数学" },
  },
  {
    id: "set3-20",
    top: "計",
    left: "予",
    right: "数",
    bottom: "出",
    answer: "算",
    words: { top: "計算", left: "予算", right: "算数", bottom: "算出" },
  },
  {
    id: "set3-21",
    top: "会",
    left: "合",
    right: "算",
    bottom: "画",
    answer: "計",
    words: { top: "会計", left: "合計", right: "計算", bottom: "計画" },
  },
  {
    id: "set3-22",
    top: "計",
    left: "映",
    right: "家",
    bottom: "面",
    answer: "画",
    words: { top: "計画", left: "映画", right: "画家", bottom: "画面" },
  },
  {
    id: "set3-23",
    top: "油",
    left: "挿",
    right: "本",
    bottom: "画",
    answer: "絵",
    words: { top: "油絵", left: "挿絵", right: "絵本", bottom: "絵画" },
  },
  {
    id: "set3-24",
    top: "校",
    left: "国",
    right: "手",
    bottom: "詞",
    answer: "歌",
    words: { top: "校歌", left: "国歌", right: "歌手", bottom: "歌詞" },
  },
  {
    id: "set3-25",
    top: "名",
    left: "作",
    right: "線",
    bottom: "目",
    answer: "曲",
    words: { top: "名曲", left: "作曲", right: "曲線", bottom: "曲目" },
  },
  {
    id: "set3-26",
    top: "大",
    left: "発",
    right: "量",
    bottom: "優",
    answer: "声",
    words: { top: "大声", left: "発声", right: "声量", bottom: "声優" },
  },
  {
    id: "set3-27",
    top: "先",
    left: "口",
    right: "脳",
    bottom: "痛",
    answer: "頭",
    words: { top: "先頭", left: "口頭", right: "頭脳", bottom: "頭痛" },
  },
  {
    id: "set3-28",
    top: "洗",
    left: "素",
    right: "色",
    bottom: "面",
    answer: "顔",
    words: { top: "洗顔", left: "素顔", right: "顔色", bottom: "顔面" },
  },
  {
    id: "set3-29",
    top: "科",
    left: "注",
    right: "的",
    bottom: "標",
    answer: "目",
    words: { top: "科目", left: "注目", right: "目的", bottom: "目標" },
  },
  {
    id: "set3-30",
    top: "入",
    left: "人",
    right: "調",
    bottom: "実",
    answer: "口",
    words: { top: "入口", left: "人口", right: "口調", bottom: "口実" },
  },
  {
    id: "set3-31",
    top: "選",
    left: "相",
    right: "紙",
    bottom: "術",
    answer: "手",
    words: { top: "選手", left: "相手", right: "手紙", bottom: "手術" },
  },
  {
    id: "set3-32",
    top: "満",
    left: "不",
    right: "音",
    bottom: "跡",
    answer: "足",
    words: { top: "満足", left: "不足", right: "足音", bottom: "足跡" },
  },
  {
    id: "set3-33",
    top: "手",
    left: "船",
    right: "相",
    bottom: "都",
    answer: "首",
    words: { top: "手首", left: "船首", right: "首相", bottom: "首都" },
  },
  {
    id: "set3-34",
    top: "急",
    left: "看",
    right: "気",
    bottom: "院",
    answer: "病",
    words: { top: "急病", left: "看病", right: "病気", bottom: "病院" },
  },
  {
    id: "set3-35",
    top: "病",
    left: "入",
    right: "長",
    bottom: "内",
    answer: "院",
    words: { top: "病院", left: "入院", right: "院長", bottom: "院内" },
  },
  {
    id: "set3-36",
    top: "名",
    left: "獣",
    right: "師",
    bottom: "学",
    answer: "医",
    words: { top: "名医", left: "獣医", right: "医師", bottom: "医学" },
  },
  {
    id: "set3-37",
    top: "新",
    left: "農",
    right: "局",
    bottom: "品",
    answer: "薬",
    words: { top: "新薬", left: "農薬", right: "薬局", bottom: "薬品" },
  },
  {
    id: "set3-38",
    top: "幸",
    left: "強",
    right: "動",
    bottom: "命",
    answer: "運",
    words: { top: "幸運", left: "強運", right: "運動", bottom: "運命" },
  },
  {
    id: "set3-39",
    top: "冷",
    left: "平",
    right: "止",
    bottom: "養",
    answer: "静",
    words: { top: "冷静", left: "平静", right: "静止", bottom: "静養" },
  },
  {
    id: "set3-40",
    top: "競",
    left: "快",
    right: "者",
    bottom: "行",
    answer: "走",
    words: { top: "競走", left: "快走", right: "走者", bottom: "走行" },
  },
  {
    id: "set3-41",
    top: "水",
    left: "遠",
    right: "法",
    bottom: "力",
    answer: "泳",
    words: { top: "水泳", left: "遠泳", right: "泳法", bottom: "泳力" },
  },
  {
    id: "set3-42",
    top: "以",
    left: "下",
    right: "雨",
    bottom: "水",
    answer: "降",
    words: { top: "以降", left: "下降", right: "降雨", bottom: "降水" },
  },
  {
    id: "set3-43",
    top: "交",
    left: "普",
    right: "学",
    bottom: "路",
    answer: "通",
    words: { top: "交通", left: "普通", right: "通学", bottom: "通路" },
  },
  {
    id: "set3-44",
    top: "経",
    left: "通",
    right: "去",
    bottom: "程",
    answer: "過",
    words: { top: "経過", left: "通過", right: "過去", bottom: "過程" },
  },
  {
    id: "set3-45",
    top: "放",
    left: "発",
    right: "料",
    bottom: "金",
    answer: "送",
    words: { top: "放送", left: "発送", right: "送料", bottom: "送金" },
  },
  {
    id: "set3-46",
    top: "連",
    left: "定",
    right: "日",
    bottom: "息",
    answer: "休",
    words: { top: "連休", left: "定休", right: "休日", bottom: "休息" },
  },
  {
    id: "set3-47",
    top: "学",
    left: "復",
    right: "慣",
    bottom: "字",
    answer: "習",
    words: { top: "学習", left: "復習", right: "習慣", bottom: "習字" },
  },
  {
    id: "set3-48",
    top: "訓",
    left: "試",
    right: "習",
    bottom: "乳",
    answer: "練",
    words: { top: "訓練", left: "試練", right: "練習", bottom: "練乳" },
  },
  {
    id: "set3-49",
    top: "好",
    left: "強",
    right: "査",
    bottom: "子",
    answer: "調",
    words: { top: "好調", left: "強調", right: "調査", bottom: "調子" },
  },
  {
    id: "set3-50",
    top: "研",
    left: "改",
    right: "理",
    bottom: "学",
    answer: "修",
    words: { top: "研修", left: "改修", right: "修理", bottom: "修学" },
  },
  {
    id: "set3-51",
    top: "出",
    left: "全",
    right: "体",
    bottom: "長",
    answer: "身",
    words: { top: "出身", left: "全身", right: "身体", bottom: "身長" },
  },
  {
    id: "set3-52",
    top: "毛",
    left: "脱",
    right: "膚",
    bottom: "肉",
    answer: "皮",
    words: { top: "毛皮", left: "脱皮", right: "皮膚", bottom: "皮肉" },
  },
  {
    id: "set3-53",
    top: "軟",
    left: "背",
    right: "折",
    bottom: "格",
    answer: "骨",
    words: { top: "軟骨", left: "背骨", right: "骨折", bottom: "骨格" },
  },
  {
    id: "set3-54",
    top: "出",
    left: "貧",
    right: "液",
    bottom: "管",
    answer: "血",
    words: { top: "出血", left: "貧血", right: "血液", bottom: "血管" },
  },
  {
    id: "set3-55",
    top: "休",
    left: "消",
    right: "吹",
    bottom: "子",
    answer: "息",
    words: { top: "休息", left: "消息", right: "息吹", bottom: "息子" },
  },
  {
    id: "set3-56",
    top: "大",
    left: "前",
    right: "分",
    bottom: "島",
    answer: "半",
    words: { top: "大半", left: "前半", right: "半分", bottom: "半島" },
  },
  {
    id: "set3-57",
    top: "半",
    left: "離",
    right: "国",
    bottom: "民",
    answer: "島",
    words: { top: "半島", left: "離島", right: "島国", bottom: "島民" },
  },
  {
    id: "set3-58",
    top: "出",
    left: "集",
    right: "物",
    bottom: "台",
    answer: "荷",
    words: { top: "出荷", left: "集荷", right: "荷物", bottom: "荷台" },
  },
  {
    id: "set3-59",
    top: "新",
    left: "玄",
    right: "作",
    bottom: "粒",
    answer: "米",
    words: { top: "新米", left: "玄米", right: "米作", bottom: "米粒" },
  },
  {
    id: "set3-60",
    top: "画",
    left: "表",
    right: "接",
    bottom: "積",
    answer: "面",
    words: { top: "画面", left: "表面", right: "面接", bottom: "面積" },
  },
  {
    id: "set3-61",
    top: "面",
    left: "体",
    right: "雪",
    bottom: "極",
    answer: "積",
    words: { top: "面積", left: "体積", right: "積雪", bottom: "積極" },
  },
  {
    id: "set3-62",
    top: "積",
    left: "消",
    right: "端",
    bottom: "度",
    answer: "極",
    words: { top: "積極", left: "消極", right: "極端", bottom: "極度" },
  },
  {
    id: "set3-63",
    top: "極",
    left: "温",
    right: "胸",
    bottom: "数",
    answer: "度",
    words: { top: "極度", left: "温度", right: "度胸", bottom: "度数" },
  },
  {
    id: "set3-64",
    top: "気",
    left: "保",
    right: "度",
    bottom: "泉",
    answer: "温",
    words: { top: "気温", left: "保温", right: "温度", bottom: "温泉" },
  },
  {
    id: "set3-65",
    top: "寒",
    left: "保",
    right: "蔵",
    bottom: "水",
    answer: "冷",
    words: { top: "寒冷", left: "保冷", right: "冷蔵", bottom: "冷水" },
  },
  {
    id: "set3-66",
    top: "発",
    left: "加",
    right: "帯",
    bottom: "心",
    answer: "熱",
    words: { top: "発熱", left: "加熱", right: "熱帯", bottom: "熱心" },
  },
  {
    id: "set3-67",
    top: "熱",
    left: "携",
    right: "状",
    bottom: "電",
    answer: "帯",
    words: { top: "熱帯", left: "携帯", right: "帯状", bottom: "帯電" },
  },
  {
    id: "set3-68",
    top: "電",
    left: "大",
    right: "紋",
    bottom: "動",
    answer: "波",
    words: { top: "電波", left: "大波", right: "波紋", bottom: "波動" },
  },
  {
    id: "set3-69",
    top: "火",
    left: "衛",
    right: "座",
    bottom: "空",
    answer: "星",
    words: { top: "火星", left: "衛星", right: "星座", bottom: "星空" },
  },
  {
    id: "set3-70",
    top: "太",
    left: "夕",
    right: "気",
    bottom: "光",
    answer: "陽",
    words: { top: "太陽", left: "夕陽", right: "陽気", bottom: "陽光" },
  },
  {
    id: "set3-71",
    top: "親",
    left: "旧",
    right: "人",
    bottom: "情",
    answer: "友",
    words: { top: "親友", left: "旧友", right: "友人", bottom: "友情" },
  },
  {
    id: "set3-72",
    top: "友",
    left: "表",
    right: "報",
    bottom: "熱",
    answer: "情",
    words: { top: "友情", left: "表情", right: "情報", bottom: "情熱" },
  },
  {
    id: "set3-73",
    top: "情",
    left: "速",
    right: "告",
    bottom: "道",
    answer: "報",
    words: { top: "情報", left: "速報", right: "報告", bottom: "報道" },
  },
  {
    id: "set3-74",
    top: "報",
    left: "広",
    right: "白",
    bottom: "知",
    answer: "告",
    words: { top: "報告", left: "広告", right: "告白", bottom: "告知" },
  },
  {
    id: "set3-75",
    top: "告",
    left: "通",
    right: "識",
    bottom: "恵",
    answer: "知",
    words: { top: "告知", left: "通知", right: "知識", bottom: "知恵" },
  },
  {
    id: "set3-76",
    top: "知",
    left: "常",
    right: "別",
    bottom: "字",
    answer: "識",
    words: { top: "知識", left: "常識", right: "識別", bottom: "識字" },
  },
  {
    id: "set3-77",
    top: "一",
    left: "当",
    right: "号",
    bottom: "組",
    answer: "番",
    words: { top: "一番", left: "当番", right: "番号", bottom: "番組" },
  },
  {
    id: "set3-78",
    top: "番",
    left: "赤",
    right: "合",
    bottom: "織",
    answer: "組",
    words: { top: "番組", left: "赤組", right: "組合", bottom: "組織" },
  },
  {
    id: "set3-79",
    top: "番",
    left: "記",
    right: "令",
    bottom: "外",
    answer: "号",
    words: { top: "番号", left: "記号", right: "号令", bottom: "号外" },
  },
];
